version: '2.1'
services:
  smtp:
    build:
      context: .
      args:
        - DUMB_INIT_VER=1.2.1
        - EXT_DOMAIN=localdomain
        - EXT_HOST=localhost
        - LOCAL_DELIVER=localhost
        - MESSAGE_SIZE_LIMIT=26214400
        - SRC_NETWORKS=127.0.0.0/8 [::1]/128 172.16.0.0/12
        - SECURITY_OPTIONS=noanonymous
    env_file:
      - config.env
    image: knobby-docker-postfix
    ports:
      - "25:25"
    restart: always
networks:
  default:
    external:
      name: docker_default
